name: Generate & push changelog (master only)
on:
  push:
    branches: [master]

jobs:
  generate-push-changelog:
    name: Generate & push changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.ALLOWED_GITHUB_TOKEN }}
      - uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247 # renovate: tag=v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@998652d28d7702d095d40f52ae42982a80ae8c7d # tag=v9.0.1
        with:
          add: CHANGELOG.md
          default_author: github_actions
          message: "Commit last changes to CHANGELOG.md"
