name: Terraform plan validation (PRs only)

on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write

jobs:
  examples_hcloud-k3s:
    name: Hetzner Cloud
    if: ${{ github.event.label.name == 'terraform:plan' }}
    permissions:
      pull-requests: write
    secrets:
      env: |
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.plan.yaml@42f3d38aa983309e49769c5ef3736746bb1ddf39
    with:
      terraform_vars: |
        ssh_key: ''
      terraform_workdir: examples/hcloud-k3s

  unlabel-pull-request:
    if: always()
    name: Remove 'terraform:plan' label
    needs: [examples_hcloud-k3s]
    runs-on: ubuntu-latest
    steps:
      - name: Unlabel 'terraform:plan'
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          labels: terraform:plan
